spring:
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: all-messages
        processor-in-0:
          destination: all-messages
          group: default
        processor-out-0:
          destination: processed-messages
        consumer-in-0:
          destination: processed-messages
          group: default
      function:
        definition: consumer;processor
      source: producer;processor
