spring:
  cloud:
    stream:
      bindings:
        consumer-in-0:
          destination: demo-destination
          group: demo-group
        producer-out-0:
          destination: demo-destination
      function:
        definition: consumer
      source: producer
