spring:
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: unfiltered

        filter1-in-0:
          destination: unfiltered
          group: default
        filter1-out-0:
          destination: filter2

        filter2-in-0:
          destination: filter2
          group: default
        filter2-out-0:
          destination: filter3

        filter3-in-0:
          destination: filter3
          group: default
        filter3-out-0:
          destination: filtered

        consumer-in-0:
          destination: filtered
          group: default

      function:
        definition: consumer;filter1;filter2;filter3
      source: producer;filter1;filter2;filter3
