spring:
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: unfiltered

        spamFilter-in-0:
          destination: unfiltered
          group: default
        spamFilter-out-0:
          destination: profanityFilter

        profanityFilter-in-0:
          destination: profanityFilter
          group: default
        profanityFilter-out-0:
          destination: negativityFilter

        negativityFilter-in-0:
          destination: negativityFilter
          group: default
        negativityFilter-out-0:
          destination: filtered

        consumer-in-0:
          destination: filtered
          group: default

      function:
        definition: consumer;spamFilter;profanityFilter;negativityFilter
      source: producer;spamFilter;profanityFilter;negativityFilter
