spring:
  cloud:
    stream:
      bindings:
        profanityFilter-in-0:
          destination: profanityFilter
          group: default
        profanityFilter-out-0:
          destination: negativityFilter
      function:
        definition: profanityFilter
      source: profanityFilter
